// Generated by CoffeeScript 1.8.0
(function() {
  var brainfuck, expect, _;

  brainfuck = require('..');

  expect = require('expect.js');

  _ = require('lodash');

  describe('program basics', function() {
    it('can run a simple program', function() {
      var program;
      program = brainfuck(',+.>,+.');
      program.run('gh');
      expect(program.resultString()).to.be('hi');
      expect(program.results).to.eql([104, 105]);
      expect(program.tape).to.eql([104, 105]);
      return expect(program.instructionsRun).to.eql(7);
    });
    it('can run a simple program by specifying src as options', function() {
      var program;
      program = brainfuck({
        src: ',+.>,+.'
      });
      program.run('gh');
      return expect(program.resultString()).to.be('hi');
    });
    return it('can run "hello world"', function() {
      var program;
      program = brainfuck(['++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>', '---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.'].join(''));
      program.run();
      expect(program.resultString()).to.be('Hello World!\n');
      return expect(program.instructionsRun).to.eql(986);
    });
  });

}).call(this);
