// Generated by CoffeeScript 1.8.0
(function() {
  var brainfuck, expect, _;

  brainfuck = require('..');

  expect = require('expect.js');

  _ = require('lodash');

  describe('register bounds', function() {
    it('can bound the values negatively', function() {
      var program;
      program = brainfuck({
        src: '>+>->--',
        minValue: -1
      });
      program.run();
      return expect(program.tape).to.eql([0, 1, -1, -1]);
    });
    it('can bound the values positively', function() {
      var program;
      program = brainfuck({
        src: '>->+>++',
        maxValue: 1
      });
      program.run();
      return expect(program.tape).to.eql([0, -1, 1, 1]);
    });
    it('can bound the values on both sides', function() {
      var program;
      program = brainfuck({
        src: '>->-->--->+>++>+++',
        minValue: -1,
        maxValue: 1
      });
      program.run();
      return expect(program.tape).to.eql([0, -1, -1, -1, 1, 1, 1]);
    });
    return it('can wrap around', function() {
      var program;
      program = brainfuck({
        src: '--->+++++++++++',
        minValue: -1,
        maxValue: 10,
        wrap: true
      });
      program.run();
      return expect(program.tape).to.eql([9, -1]);
    });
  });

}).call(this);
